#!/bin/busybox ash

# mount /proc and /sys
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys

# mount tmpfs on /tmp (system memory)
/bin/busybox mount -t tmpfs tmp /tmp

# symbolic links
export PATH=/bin:/bin/links

# loop back interface
/bin/busybox ip link dev lo set up

# devices sdk setup
export OPERA_FONTS=/fonts
export OPERA_DIR=/opera_dir
export OPERA_HOME=/opera_home

# launch webos interface
/bin/opera -u file:///resources/start-page.html
